### ISSUE TITLE
AaD, I want to clean up the Movie Card so it is up to date and clean, both visually and code-wise

### ISSUE THREAD

**Issue by samsaksfithian** [yamovie/client#196]
- [x] Fully transition from TMDB data to JW data
  - Currently, the movie card does a lot of checking so it doesn't break whether it's getting data in the TMDB or JW format
  - Since we are fully transitioning to JW data, this checking is no longer necessary
- [x] Use some of the layout/design ideas from the redesigned MovieFeedItem to make things look a little nicer (handled in #209 )
- [x] Also implement the text resizing as mentioned in #185 
- [x] Handle the default data bug as mentioned in #206
